#!/usr/bin/python

from cov_test import trace_to_prediction
from pylab import csv2rec
import sys

# trace_to_prediction(tracefile, lon, lat, t, covariate_values, ntot, burn=0)

doc_str = doc_str = """cov-test-predict dbname input.csv ntot burn
- dbname: The filename used for the trace.
- input.csv: A csv file whose column names are lat, lon, t, pos, neg and the names of any covariates used.
- ntot: The total number of predictions to make.
- burn: The number of burnin iterations to discard.
"""

if len(sys.argv)==0:
    print doc_str
    sys.exit()
if sys.argv[1] in ['-h','--help']:
    print doc_str
    sys.exit()

tracefile = sys.argv[1]
input = sys.argv[2]
ntot = int(sys.argv[3])
burn = int(sys.argv[4])

input = csv2rec(input)
lon = input.lon
lat = input.lat
t = input.t
pos = input.pos
neg = input.neg

cv = {}
for n in input.dtype.names:
    if n not in ['lon','lat','t','pos','neg']:
        cv[n]=input[n]

samps = trace_to_prediction(tracefile, lon, lat, t, cv, ntot, burn=0)
samps.tofile(tracefile.replace('.hdf5','')+'_samps.csv',sep=',')